import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 1,
    title: '사용자간 직거래 몰 React Native 앱 개발',
    area: '개발>앱',
    type: 'budget',
    status: '모집중',
    categories: ['개발'],
    skills: ['React Native', 'Android', 'iOS'],
    quoteHigh: 11000,
    quoteLow: 7000,
    averageEstimate: 7964,
    averagePeriodDays: 120,
    applicants: 25,
    deadlineDays: 9,
    postedAt: '2026-05-14',
    summary: '거래, 결제, 회원 관리가 포함된 모바일 앱과 관리자 기능을 함께 제작합니다.',
  },
  {
    id: 2,
    title: '간단한 병원 지점별 관리 및 정보제공 앱 개발(Android, IOS)',
    area: '개발>앱',
    type: 'budget',
    status: '마감',
    categories: ['개발'],
    skills: ['React Native', 'Figma', 'Node.js'],
    quoteHigh: 1400,
    quoteLow: 800,
    averageEstimate: 1080,
    averagePeriodDays: 45,
    applicants: 13,
    deadlineDays: 2,
    postedAt: '2026-05-12',
    summary: '병원 지점별 안내, 관리, 정보 제공을 위한 Android/iOS 앱을 개발합니다.',
  },
  {
    id: 3,
    title: '요트투어 중개 플랫폼 Hybrid 앱개발',
    area: '개발>앱',
    type: 'budget',
    status: '모집중',
    categories: ['개발'],
    skills: ['Hybrid App', 'Payment', 'Admin'],
    quoteHigh: 2500,
    quoteLow: 1800,
    averageEstimate: 2140,
    averagePeriodDays: 90,
    applicants: 15,
    deadlineDays: 14,
    postedAt: '2026-05-10',
    summary: '투어 상품 등록, 예약, 결제, 리뷰 기능을 포함한 중개 플랫폼 앱 개발입니다.',
  },
  {
    id: 4,
    title: '홍채 등록/인식 Android 앱개발',
    area: '개발>앱',
    type: 'budget',
    status: '모집중',
    categories: ['개발'],
    skills: ['Android', 'Biometric', 'Java'],
    quoteHigh: 1300,
    quoteLow: 1200,
    averageEstimate: 1278,
    averagePeriodDays: 60,
    applicants: 9,
    deadlineDays: 19,
    postedAt: '2026-05-09',
    summary: '홍채 정보를 등록하고 인식 결과를 확인하는 Android 기반 앱 개발입니다.',
  },
  {
    id: 5,
    title: '간단한 작가 작품 소개용 모바일 웹 개발',
    area: '개발>모바일웹',
    type: 'budget',
    status: '모집중',
    categories: ['개발', '디자인'],
    skills: ['HTML5', 'CSS', 'Mobile Web'],
    quoteHigh: 350,
    quoteLow: 150,
    averageEstimate: 242,
    averagePeriodDays: 21,
    applicants: 19,
    deadlineDays: 6,
    postedAt: '2026-05-08',
    summary: '작가 소개와 작품 갤러리를 모바일에 최적화해 보여주는 웹 페이지를 제작합니다.',
  },
  {
    id: 6,
    title: '슈즈 사용자거래 오픈마켓 웹개발',
    area: '개발>웹',
    type: 'budget',
    status: '모집중',
    categories: ['개발'],
    skills: ['React', 'Spring', 'MySQL'],
    quoteHigh: 2223,
    quoteLow: 1500,
    averageEstimate: 1894,
    averagePeriodDays: 60,
    applicants: 8,
    deadlineDays: 12,
    postedAt: '2026-05-07',
    summary: '상품 등록, 거래, 결제, 판매자/구매자 관리가 포함된 오픈마켓 웹입니다.',
  },
  {
    id: 7,
    title: '교수&학생 간 슬라이드 실시간공유 웹개발',
    area: '개발>웹',
    type: 'budget',
    status: '마감',
    categories: ['개발'],
    skills: ['WebSocket', 'React', 'Node.js'],
    quoteHigh: 5000,
    quoteLow: 2800,
    averageEstimate: 3589,
    averagePeriodDays: 60,
    applicants: 9,
    deadlineDays: 1,
    postedAt: '2026-05-05',
    summary: '강의 중 슬라이드를 실시간으로 공유하고 참여 상태를 확인하는 웹서비스입니다.',
  },
  {
    id: 8,
    title: '산업지수 및 기업리포트 데이터 출력 웹개발',
    area: '개발>웹',
    type: 'budget',
    status: '모집중',
    categories: ['개발', '기획'],
    skills: ['Data Visualization', 'React', 'API'],
    quoteHigh: 1200,
    quoteLow: 1000,
    averageEstimate: 1156,
    averagePeriodDays: 60,
    applicants: 9,
    deadlineDays: 8,
    postedAt: '2026-05-04',
    summary: '산업지수와 기업 리포트 데이터를 검색하고 시각화하는 웹 화면을 개발합니다.',
  },
  {
    id: 9,
    title: 'CAM & CAD 호환 소프트웨어 개발',
    area: '개발>프로그램',
    type: 'budget',
    status: '마감',
    categories: ['개발'],
    skills: ['C++', 'CAD', 'Windows'],
    quoteHigh: 5000,
    quoteLow: 4400,
    averageEstimate: 4800,
    averagePeriodDays: 150,
    applicants: 3,
    deadlineDays: 4,
    postedAt: '2026-05-02',
    summary: 'CAM과 CAD 파일 호환 및 가공 데이터를 처리하는 윈도우 소프트웨어 개발입니다.',
  },
  {
    id: 10,
    title: '프린터 스캐너 제어용 윈도우 SW 개발',
    area: '개발>프로그램',
    type: 'budget',
    status: '모집중',
    categories: ['개발'],
    skills: ['Windows', 'C#', 'Device Control'],
    quoteHigh: 500,
    quoteLow: 300,
    averageEstimate: 363,
    averagePeriodDays: 14,
    applicants: 8,
    deadlineDays: 11,
    postedAt: '2026-05-01',
    summary: '장비 제어와 스캔 데이터 처리를 위한 윈도우 기반 프로그램을 개발합니다.',
  },
]
